language: java

jdk:
  - openjdk11

addons:
  chrome: stable
  sonarcloud:
    organization: ttbmp
    token:
      secure: "JW5qfx6YasWVL9oBRrU5H5slEHe1Coh/ayL2b4YuS23a/6Q6hB3kmMura2xZpQLFVm46KS1kWJKPPv0499u9pQjfu5wovh105NKdO0v7Pdkuo/4NGcIDW2TJaTJXfJ/7fHbELdGG8z/1Rc34jh5otfX7jrOY1wf0boMRc1F++s7C10W2q4wXSkxqvkpqHnN8l58DOX0FyZiX7HU4pmvu0vccpt+oxIDqaEOQGdGG0z88TUzCWWr0iTfTwygE2unALT+AwOt97bp4RPaxjibuv06rObsXztRHoaI4w4hTHzFjd+T9oEkadgaslpTeBYZghpwmw4gEg5e9bw42Lqykj58FXWQCgM1c9jwP9v/uFERYMig3mWKnF5WtotDYfgmzjvy1woY2O4uz7YDzUuc1feiYk3rQQhw6271/yiCT/P+cZbfUnFmVTYIsO7RWH6cdkKA0RUq2qXVLw9VOWigPlkETky8fGf1PZs+O/FbprffKHaQzjeu9rKHIb8CB98j+qImrwuO5pI3ncH0J7qe74hI/qnb5CmIr8G8LikKewJNsGwcGlpIsZ9lFBjU4QpXgNbMSedAF5ZxukHJi8OByPwJMLUdapXdBOaziU+ZYSvuae47+CkrK6adbJHhG4o035+ZHmTRkLCZ1hhj9riqxvyIbePK9lyy0l/VczPbVA8g="

before_install:
  - chmod +x gradlew

script:
  - "./gradlew build"
  - "./gradlew sonarqube"
