language: java

jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "green-organization"

before_install:
  - chmod +x gradlew

script:
  - "./gradlew build"
  - "./gradlew sonarqube"

env:
  global:
    secure: HdkJCT5cPJIf4VfAn8FxHTd+I1CY9XepO5hGvkLUla+Bk3RxrTmJ+Z2C1oV5appFYEhhhsho5CefXOECbPz4GQ8iaJKxqo1kNYEQPphYqGXAiftYcrheLEIu6OmhxeBz6fnxgI4oXZLfpbdI1PlWV03bHMaGg/7RjFt6BkSm517wa+38nazYY55Y/f37SsV+mfUK6p5cFwPHUa7Tmnw4ndQ1zexp+7aotC/9djzHhNuMeO/Amwo0FUYm5noTNstBv/fVS751vXLaLmnhCzQOZ5Jbj+ZQ0xI2jL1aWop97OFEXOjdhvrZleWp6KsvZj8dZJTDhX4PB5caA+pkZknT4rJHmym15IjocI2sOsinObmNIHHJ/YuOWFmSTCNQCNTfKJP+SoWWIyCGh1z3+trb/DnVylqRKwCt7ypzk3yqF/2fXTbmeBekrwZr4ir6+wV3pdcZ2TZdKtBFWmFAhKI7ZUDURnupIGISxGNr6bruwmFNUdlh5Pn+u1W7XZwO83QsZOgjQ1lsKwnXuLmyroNN+aBgFXbdumLs2O+HH4yEeTAK7EM3Z/zTyCqgwDwRpfsNp3qwSZLOrDYNkZyQsbmUtBUGA0P7Pwp68VngMPB/bFMUXylZ4T2Fkcjy4prhlH/Lt/cfaPnE0YizVzTxkHAVhaxp59xgXu6y9MobGMdeR1U=
