language: java

jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "ttbmp"

before_install:
  - chmod +x gradlew

script:
  - "./gradlew build"
  - "./gradlew sonarqube"

env:
  global:
    secure: cpeQVQZP0UCbVJeGRqj6FPSItd/wwgJAlS/NVY4zyXKAgT4qJgkhlP64D7UxfYD49AYE5Dh0jtMmPg+Bi1i1RWKiyp8VGluW32rAA7VDzBh7lZ9ijjiuIfOkeCOIHIicpEMRV2Py9/JB7Z9e0/78x+cf6UJkndeG5Q7C33AvHuPnabATEtEZbG5UpzgbF8KtqN1TH4HNrGPdVNDI1T1ICOWaFF1mScN3fhQwrvhUc1yX6gTwD2m8xSdcx78sOAv8Vp2JdyZqlNMDdr98uiR+KAurcynvwmvWePilFJGCQ+rQKPNXRTNjc7XImyYeYkNTcGLBvYeHrvIyqsydrjsr5joO/i8IqMCF4x9BtupkF1P6MBF6jwKokF80OdnA9GvJMSz1sxpatkqTkos3/wz37+DEtyEtYYbX2Bq3MyQFxosn3tZ59utJQ8J88eV2n2CpzEbsBx4XN0XEdwG3UGQPbAdxiCzRQdkHs0+fxUyJr/RjgUgvQgZr+Oju7VVvk6dO2TPydIqCrSD+gwz7e9GcOwzMhBGsqY9NnLKKYrzGtPj7PxhwoyDqPGtwZTOkPOpdAPglT2K3fOBjV4sLJmherpnh1UIrWzJAZ4zkdTJplmWLztNKLRocAGtbuh4XwK3z1gTsU+/6cf89okyKZlAaCevMglZK3CT5JZIHNG7iT9I=
