language: java

jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: ttbmp

before_install:
  - chmod +x gradlew

script:
  - "./gradlew build"
  - "./gradlew sonarqube --s"

env:
  global:
    secure: ps8ngUOJ26IRBExweWlNkg9Fh5funcB6WduzN8YDFVW8L07bJGuqd0SXkfx46oiiqpIAvvCMcjpn81EMVeqt5SK9nxMWIeLFQMn5vTmpFHRuu3z2qYPF0M4ALDL0kgn5/iEJZCBoUPwGToOVm8Qz2MULWLte6CX2C/hmnfkpy7TxfJFSvwUtt0xhyCZO8IJfU5eZCYI88Ovc/eANgERJxe5Zel+xgF3UTykyE8DPjgZRn82Cgya0UWaSBtOk3Rv8ok+XjFilbgNvfah53FO65boI2lWSNG3BLGiAHKD5ApF1Iw1jOCBOLd8GTYZILskuvho2EXsYma5/S0seAaBZlHr4TLvGTjzILpFDENJtVpRayqU56UlLWkSSjoRTp7nv5B61Ude1eAEgyXTazHRM7SXCbM81PMF5Hq4MhvCaYfQUTUypTz0EDP7XxtEcjlupCeZap8Dmt8Uc5IIP83NjuR5o6gQMKkxTB+XAAlesAnZXMyM1luj0eVSe5YczFHZnAJp1wk5JRhzL5JFY7lu1Ag5suR0uWuTmp9fyMVWtVAmJPjpQ22KklEg+iBHF0mtBaRGHqbySEDRzWETxWRTpjDf2qDhkEgRGGltjm6M9QMID8qOrr3zCJOCH1yDGSgFVx22xjlEqqrc9/SUN1WsfVF+5Yx4EOsoaNjQriQOV2dc=
