/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ttbmp.cinehub.app;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class MessageUtilsTest {
    @Test public void testGetMessage() {
        String message = "Hello, JavaFX " +
                System.getProperty("javafx.version") +
                "\nRunning on Java " +
                System.getProperty("java.version") +
                ".";
        assertEquals(message, MessageUtils.getMessage());
    }
}
