/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ttbmp.cinehub.app;

public class Example {
    public static void main(String[] args) {
        System.out.println(MessageUtils.getMessage());
    }
}
