/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ttbmp.cinehub.core;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class ExampleTest {

    @Test public void testConstructor() {
        assertEquals(1, new Example().foo());
    }

}
