/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ttbmp.cinehub.webapp;

class MessageUtils {
    public static String getMessage() {
        return "Hello world!";
    }
}
