/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.ttbmp.cinehub.java-application-conventions")
}

dependencies {
    implementation(project(":core"))
    implementation(project(":data"))
}

application {
    // Define the main class for the application.
    mainClass.set("com.ttbmp.cinehub.webapp.Example")
}
