name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.23
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v2
      - name: Setup database
        run: |
          mysql --host 127.0.0.1 --port 3306 -uroot -ppassword < ./data/local/src/main/resources/cinemadb.sql
          mysql --host 127.0.0.1 --port 3306 -uroot -ppassword -e 'call popola();' cinemadb
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
      - name: Setup Chrome driver
        uses: nanasess/setup-chromedriver@master
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: |
          ./gradlew :app:client:web:run &
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          ./gradlew build
      - name: Sonarqube scan
        run: ./gradlew sonarqube
