name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.23
        ports:
          - 3306:3306
        env:
          MYSQL_USER: admin
          MYSQL_PASSWORD: admin
          MYSQL_ROOT_PASSWORD: admin
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v2
      - name: Shutdown Ubuntu MySQL
        run: |
          sudo service mysql --version
          sudo service mysql status
          sudo service mysql stop
      - name: Setup database
        run: |
          mysql -h localhost -P $PORT -u $MYSQL_USER -p$MYSQL_ROOT_PASSWORD --version
          mysql -h localhost -P $PORT -u $MYSQL_USER -p$MYSQL_ROOT_PASSWORD < ./data/local/src/main/resources/cinemadb.sql
        env:
          PORT: ${{ job.services.mysql.ports[3306] }}
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
      - name: Setup Chrome Driver
        uses: nanasess/setup-chromedriver@v1.0.1
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          ./gradlew :app:client:web:run &
          ./gradlew build
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
      - name: Sonarqube scan
        run: ./gradlew sonarqube
