name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    container: ubuntu

    services:
      mysql:
        image: mysql:8.0.23
        env:
          MYSQL_ROOT_PASSWORD: password
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v2
      - name: Setup database
        run: |
          apt-get update
          apt-get install -y mysql-client
          mysql --host mysql -uroot -ppassword < ./data/local/src/main/resources/cinemadb.sql
          mysql --host mysql -uroot -ppassword -e 'call popola();' cinemadb
      - name: Setup Chrome web driver
        run: apt-get install google-chrome-stable
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: |
          ./gradlew :app:client:web:run &
          xvfb-run --server-args=\"-screen 0 1024x768x24\" ./gradlew build
      - name: Sonarqube scan
        run: ./gradlew sonarqube
